#!/bin/sh
printf '\e[1;33mWelcome to Maple Linux!\e[0m\n'
sysctl -pq

mkdir -p /cache/chronyd
respawn -d 1 chronyd -n &

# Is this really the best way to do this? ~ahill
[ ! -c "/etc/ndhc/jail/dev/null" ] && mknod /etc/ndhc/jail/dev/null c 1 3
[ ! -c "/etc/ndhc/jail/dev/urandom" ] && mknod /etc/ndhc/jail/dev/urandom c 1 9
chown -R ndhc:dhcp /etc/ndhc/jail/var
chmod 666 /etc/ndhc/jail/dev/null
chmod 444 /etc/ndhc/jail/dev/urandom
