#!/bin/sh
printf '\e[1;33mWelcome to Maple Linux!\e[0m\n'
sysctl -pq
mkdir -p /cache

[ ! -f "/cache/log" ] && touch /cache/log
chmod 640 /cache/log
respawn -d 1 syslogd -F &

mkdir -p /cache/chronyd
respawn -d 1 chronyd -n &

[ ! -c "/etc/ndhc/jail/dev/null" ] && mknod /etc/ndhc/jail/dev/null c 1 3
chmod 666 /etc/ndhc/jail/dev/null
[ ! -c "/etc/ndhc/jail/dev/urandom" ] && mknod /etc/ndhc/jail/dev/urandom c 1 9
chmod 444 /etc/ndhc/jail/dev/urandom
chown -R ndhc:dhcp /etc/ndhc/jail/var
