timeout: {{ bootloader.timeout }}

/Maple Linux
    protocol: linux
    kernel_path: boot():/vmlinuz-maple
    kernel_cmdline: root={{ filesystem | where: "path", "/" | map: "device" }} {{ bootloader.cmdline | join: " " }}
