timeout: {{ bootloader.timeout }}

/Maple Linux
    protocol: linux
    kernel_path: boot():/vmlinuz-7.1.3-maple
    kernel_cmdline: root={% for fs in filesystem %}{% if fs.path == "/" %}{{ fs.device }}{% endif %}{% endfor %} {{ bootloader.cmdline | join: " " }}
